name: Test

on:
  push:
    branches: [ feature/github_workflow ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Execute unit tests
      run: dotnet test